"""initial tables

Revision ID: 7d7828b52d20
Revises: 
Create Date: 2026-03-04 17:16:15.248150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d7828b52d20'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projectmember')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projectmember',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('projectmember_project_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('projectmember_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('projectmember_pkey'))
    )
    # ### end Alembic commands ###
